- id: alarm_1_weekday
  alias: Wake me up (weekday)
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_1_time_minus_offset.state  }}'
  action:
  - data: {}
    service: script.good_morning

- id: gaming_mode
  alias: "Start Gaming Mode"
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - target:
      entity_id: '{{ trigger.event.data.entity_id }}'
    service: '{{ trigger.event.data.service }}'